spring:
  application:
    name: server
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 9443


discord:
  coolcodehacker:
    # It cannot be named as token. Otherwise, the env variable will override the specific profile variable... IDK why...
    token1:
    channel:

app:
  coordinator-auth-token:
  instruction-url: