spring:
  application:
    name: server
  datasource:
    url: jdbc:mariadb://host.docker.internal:3306/YourDatabaseName
    username: YourUsername
    password: YourPassword
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 9443
  servlet:
    context-path: /api

discord:
  coolcodehacker:
    # It cannot be named as token. Otherwise, the env variable will override the specific profile variable... IDK why...
    token1:
    channel:

app:
  coordinator-auth-token:
  instruction-url: