spring:
  application:
    name: server
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 9443
  servlet:
    context-path: /api

discord:
  coolcodehacker:
    # It cannot be named as token. Otherwise, the env variable will override the specific profile variable... IDK why...
    token1:
    channel:

app:
  coordinator-auth-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJjb2RlaXRzdWlzc2UyMDIyQGdtYWlsLmNvbSIsImV4cCI6MTc2MTg2ODgwMH0.8KGapch9T2AZ7Hcvzz5EHv5fSYo1sjuTwGsbSrDIJHi-hAdAfpf_qw4-bqKRs_1NO1xwCQNwkJ98UEJ6fHeAiQ
  instruction-url: