spring:
  application:
    name: server
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: sa
    password: YourStrong@Passw0rd
  jpa:
    hibernate:
      ddl-auto: update


server:
  port: 9443


discord:
  coolcodehacker:
    # It cannot be named as token. Otherwise, the env variable will override the specific profile variable... IDK why...
    token1:
    channel:

app:
  coordinator-auth-token:
  instruction-url: